-- Admin features: login activity log, DB-managed editor allowlist,
-- and note moderation (delete). Paste once in Supabase SQL Editor.
--
-- Caveat (accepted trade-off): the anon key is public in the dashboard
-- bundle, so anyone holding it can technically call these endpoints
-- directly — the app gates the UI, not the API. Same threat model as
-- the existing world-writable comment inserts.

create table if not exists auth_events (
  id bigint generated by default as identity primary key,
  email text not null,
  name text,
  page text,
  created_at timestamptz not null default now()
);
alter table auth_events enable row level security;
create policy "log logins"  on auth_events for insert with check (true);
create policy "read logins" on auth_events for select using (true);
create index idx_auth_events_email on auth_events (email, created_at desc);

create table if not exists editors (
  email text primary key,
  name text,
  added_by text,
  created_at timestamptz not null default now()
);
alter table editors enable row level security;
create policy "read editors"   on editors for select using (true);
create policy "add editors"    on editors for insert with check (true);
create policy "remove editors" on editors for delete using (true);

-- Moderation: allow note deletion (was strictly append-only).
drop policy if exists "delete notes" on outreach_comments;
create policy "delete notes" on outreach_comments for delete using (true);
